[extend]
useDefault = true

[[allowlists]]
description = "Official Stellar testnet USDC contract and issuer public addresses"
regexTarget = "match"
regexes = [
  '''CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA''',
  '''GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5''',
]
